#!/bin/python

import os, re, socket, struct, sys, time

ifstat = r'([a-z][a-z\d.-]*)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s*'
ifstat = re.compile(ifstat, re.ASCII)

header = struct.Struct('<5Q')
record = struct.Struct('<4f')

def log(fields, timestamp):
  fd = os.open(fields[0], os.O_RDWR | os.O_CREAT, 0o666)
  try:
    os.ftruncate(fd, header.size + 43200 * record.size)
    v0 = header.unpack(os.pread(fd, header.size, 0))
    v1 = (timestamp, *(int(x) for x in fields[1:5]))
    t0 = 1 + v0[0] // 60_000_000_000
    t1 = 1 + v1[0] // 60_000_000_000
    if t0 + 43200 < t1:
      os.pwrite(fd, bytearray(43200 * record.size), header.size)
      os.pwrite(fd, header.pack(*v1), 0)
    elif t0 < t1:
      packed = record.pack(
        max(1e9 * (v1[1] - v0[1]) / (v1[0] - v0[0]), 0.0),
        max(1e9 * (v1[2] - v0[2]) / (v1[0] - v0[0]), 0.0),
        max(1e9 * (v1[3] - v0[3]) / (v1[0] - v0[0]), 0.0),
        max(1e9 * (v1[4] - v0[4]) / (v1[0] - v0[0]), 0.0))
      for t in range(t0, t1):
        os.pwrite(fd, packed, header.size + (t % 43200) * record.size)
      os.pwrite(fd, header.pack(*v1), 0)
  finally:
    os.close(fd)

command = os.path.basename(sys.argv[0])
if len(sys.argv) < 3:
  print(f'Usage: {command} HOST PORT', file = sys.stderr)
  sys.exit(64)

try:
  addresses = socket.getaddrinfo(*sys.argv[1:3], type = socket.SOCK_STREAM)
  addresses = [(info[4][0], info[4][1]) for info in addresses]
except socket.gaierror as error:
  print(command, f'{sys.argv[1]}:{sys.argv[2]}', error.strerror,
    file = sys.stderr, sep = ': ')
  sys.exit(1)

while True:
  time.sleep(60 - time.time() % 60)
  for address in addresses:
    try:
      with socket.create_connection(address, 2).makefile() as stream:
        timestamp = time.time_ns()
        for line in stream:
          try:
            if match := ifstat.fullmatch(line):
              log(match.group(1, 2, 3, 4, 5), timestamp)
          except Exception as error:
            print(command, error, file = sys.stderr, sep = ': ')
            continue
        break
    except (OSError, TimeoutError):
      continue
  else:
    print(command, 'Connection failed', file = sys.stderr, sep = ': ')
