#!/bin/sh -e

for i in $(find "$@" -type f); do
  if head -c2 $i | grep -q '#!'; then
    if head -n1 $i | grep -q '^#!\( *//*usr/\| *//\| \)'; then
      echo "Fixing $i:"
      echo -n "-" && head -n1 $i
      sed -i -e '1s.^\(#! *\)//*usr//*local//*.\1/.' \
             -e '1s.^\(#! *\)//*usr//*.\1/.' -e '1s.^\(#! *\)///*.\1/.' \
             -e '1s.^\(#!\)  *.\1.' $i
      echo -n "+" && head -n1 $i && echo
    fi
    if head -n1 $i | grep -q '^#!/bin/env '; then
      echo "#!/bin/env used in $i:"
      echo -n "-" && head -n1 $i
      sed -i -e '1s.^\(#!/bin/\)env  *\([^ =][^ =]*\)\( \|$\).\1\2\3.' $i
      echo -n "+" && head -n1 $i && echo
    fi
  fi
done
