#!/bin/bash -e

find "$@" -type f -print0 | while read -d '' -r FILE; do
  if [[ $(head -c 2 "$FILE") == '#!' ]]; then
    if head -n 1 "$FILE" | grep -q '^#!\( \|//\|/usr/\|/bin/env \)'; then
      echo -n "Fixing $FILE: '$(head -n 1 "$FILE")' -> "
      sed -e '1s:^#! *//*:#!/:' \
          -e '1s:^#!/usr/local/:#!/:' \
          -e '1s:^#!/usr/:#!/:' \
          -e '1s:^#!/bin/env  *\([^ =][^ =]*\)\( \|$\):#!/bin/\1\2:' \
          -i "$FILE"
      echo "'$(head -n 1 "$FILE")'"
    fi
  fi
done
