#!/bin/sh -e

find "$@" -type f -print0 | while read -r -d "`echo -e '\0'`" file; do
  if head -c2 "$file" | grep -q '#!'; then
    if head -n1 "$file" | grep -q '^#!\( *//*usr/\| *//\| \)'; then
      echo "Fixing $file:"
      echo -n "-" && head -n1 "$file"
      sed -i -e '1s.^\(#! *\)//*usr//*local//*.\1/.' \
             -e '1s.^\(#! *\)//*usr//*.\1/.' -e '1s.^\(#! *\)///*.\1/.' \
             -e '1s.^\(#!\)  *.\1.' "$file"
      echo -n "+" && head -n1 "$file" && echo
    fi
    if head -n1 "$file" | grep -q '^#!/bin/env '; then
      echo "#!/bin/env used in $file:"
      echo -n "-" && head -n1 "$file"
      sed -i -e '1s.^\(#!/bin/\)env  *\([^ =][^ =]*\)\( \|$\).\1\2\3.' "$file"
      echo -n "+" && head -n1 "$file" && echo
    fi
  fi
done
